% FUNCTION: ROOT MEAN SQUARE ERROR     
function fcn7(filename, npr, fy, fc, fn, fy_var, fc_var, fn_var, nber,...
    dt, ft, ft_var)
K = 3; %Number of windows of analysis
j1 = 1;
for i = 1 : K
    j2 = j1 + 1;
    j3 = j1 + 2;
    j4 = j1 + 3;
    j5 = j1 + 4;
    xlswrite(filename, {['ECM: ' num2str(i)]},...
        'fstat-rmse', ['A' num2str(j1)])      
    xlswrite(filename, {['VAR: ' num2str(i)]},...
        'fstat-rmse', ['F' num2str(j1)])    
    xlswrite(filename, {'y'}, 'fstat-rmse', ['B' num2str(j1)])
    xlswrite(filename, {'c'}, 'fstat-rmse', ['C' num2str(j1)])
    xlswrite(filename, {'n'}, 'fstat-rmse', ['D' num2str(j1)])
    xlswrite(filename, {'y'}, 'fstat-rmse', ['G' num2str(j1)])
    xlswrite(filename, {'c'}, 'fstat-rmse', ['H' num2str(j1)])
    xlswrite(filename, {'n'}, 'fstat-rmse', ['I' num2str(j1)])
    xlswrite(filename, {'h=0'}, 'fstat-rmse', ['A' num2str(j2)])
    xlswrite(filename, {'h=1'}, 'fstat-rmse', ['A' num2str(j3)])
    xlswrite(filename, {'h=2'}, 'fstat-rmse', ['A' num2str(j4)])
    xlswrite(filename, {'h=3'}, 'fstat-rmse', ['A' num2str(j5)])
    xlswrite(filename, {'h=0'}, 'fstat-rmse', ['F' num2str(j2)])
    xlswrite(filename, {'h=1'}, 'fstat-rmse', ['F' num2str(j3)])
    xlswrite(filename, {'h=2'}, 'fstat-rmse', ['F' num2str(j4)])
    xlswrite(filename, {'h=3'}, 'fstat-rmse', ['F' num2str(j5)])    
    j1 = j1 + 6;
end
i = 1;
for w = 1 : K  
    i = i + 1;     
    xlswrite(filename, sqrt(mean(((dt(:, 1) - ft(:, 1))...
            .* nber(:, w, 5)).^2, 'omitnan')),...
            'fstat-rmse', ['B' num2str(i)]);   
    xlswrite(filename, sqrt(mean(((dt(:, 2) - ft(:, 2))...
            .* nber(:, w, 5)).^2, 'omitnan')),...
            'fstat-rmse', ['C' num2str(i)]);   
    xlswrite(filename, sqrt(mean(((dt(:, 3) - ft(:, 3))...
            .* nber(:, w, 5)).^2, 'omitnan')),...
            'fstat-rmse', ['D' num2str(i)]);   
    xlswrite(filename, sqrt(mean(((dt(:, 1) - ft_var(:, 1))...
            .* nber(:, w, 5)).^2, 'omitnan')),...
            'fstat-rmse', ['G' num2str(i)]);    
    xlswrite(filename, sqrt(mean(((dt(:, 2) - ft_var(:, 2))...
            .* nber(:, w, 5)).^2, 'omitnan')),...
            'fstat-rmse', ['H' num2str(i)]);    
    xlswrite(filename, sqrt(mean(((dt(:, 3) - ft_var(:, 3))...
            .* nber(:, w, 5)).^2, 'omitnan')),...
            'fstat-rmse', ['I' num2str(i)]);              
    for j = 1 : npr - 1 
        i = i + 1;
    % Root Mean Square Error (RMSE)
        xlswrite(filename, sqrt(mean(((fy(:, 3, j) - fy(:, 4, j))...
            .* nber(:, w, j)).^2, 'omitnan')),...
            'fstat-rmse', ['B' num2str(i)]);   
        xlswrite(filename, sqrt(mean(((fc(:, 3, j) - fc(:, 4, j))...
            .* nber(:, w, j)).^2, 'omitnan')),...
            'fstat-rmse', ['C' num2str(i)]);   
        xlswrite(filename, sqrt(mean(((fn(:, 3, j) - fn(:, 4, j))...
            .* nber(:, w, j)).^2, 'omitnan')),...
            'fstat-rmse', ['D' num2str(i)]);   
        xlswrite(filename, sqrt(mean(((fy_var(:, 3, j) - fy_var(:, 4, j))...
            .* nber(:, w, j)).^2, 'omitnan')),...
            'fstat-rmse', ['G' num2str(i)]);    
        xlswrite(filename, sqrt(mean(((fc_var(:, 3, j) - fc_var(:, 4, j))...
            .* nber(:, w, j)).^2, 'omitnan')),...
            'fstat-rmse', ['H' num2str(i)]);    
        xlswrite(filename, sqrt(mean(((fn_var(:, 3, j) - fn_var(:, 4, j))...
            .* nber(:, w, j)).^2, 'omitnan')),...
            'fstat-rmse', ['I' num2str(i)]);     
    end
    i = i + 2;
end



